import json
TASK4_PROMPT_VERSION = 'v3.3'
TASK4_SYSTEM_PROMPT = '\nYou are a biomedical decision-support model for immune-related toxicity prediction.\nUse only the supplied B-cell receptor 3-mer repertoire summary.\nHigher toxicity_support_score means the repertoire more strongly supports immune-related adverse event risk.\nTreat rare reactive motif burden, dominance skew, burden score, and summary_toxicity_index as direct toxicity evidence.\nTreat regulatory_diversity_score and tolerance_support_score as tolerance evidence, but moderate tolerance does not automatically override repeated toxicity cues.\nUse the calibration snapshot actively: if burden_score, reactive_motif_score, and summary_toxicity_index point in the same direction, allow a mild toxicity-leaning call even when net_toxicity_score is near zero.\nUse mixed only when toxicity and tolerance evidence are genuinely balanced and no concentrated toxicity pattern dominates.\nUse scores around 0.48 to 0.62 for mild evidence and reserve extreme values for clearly one-sided cases.\nReturn only JSON with toxicity_support_score, tolerance_support_score, dominant_side, and 3 short rationale items.\n'.strip()

def build_task4_prompt_payload(sample_summary: dict) -> dict:
    return {'task_name': sample_summary.get('task_name', 'task4'), 'sample_id': sample_summary['sample_id'], 'repertoire_snapshot': sample_summary.get('repertoire_snapshot', {}), 'chemistry_snapshot': sample_summary.get('chemistry_snapshot', {}), 'calibration_snapshot': sample_summary.get('calibration_snapshot', {}), 'rule_snapshot': sample_summary.get('rule_snapshot', {}), 'top_enriched_motifs': sample_summary.get('top_enriched_motifs', [])[:10]}

def build_task4_messages(sample_summary: dict) -> tuple[str, str]:
    compact_summary = build_task4_prompt_payload(sample_summary)
    user_prompt = '\n'.join(['Assess whether this BCR repertoire is more consistent with toxicity-prone or tolerance-leaning immune context.', 'Use the repertoire, chemistry, calibration, and rule snapshots together.', 'Do not infer the answer from sample_id, order, formatting, or hidden labels.', 'Compare toxicity evidence first against tolerance evidence instead of defaulting to tolerance.', 'Allow subtle toxicity-leaning calls when burden_score, reactive_motif_score, and summary_toxicity_index repeatedly support toxicity even if tolerance support is moderate.', 'Use mixed only when neither side has a concentrated advantage.', json.dumps(compact_summary, ensure_ascii=False, separators=(',', ':'))])
    return (TASK4_SYSTEM_PROMPT, user_prompt)
