import json
TASK5_PROMPT_VERSION = 'v0.4.1'
TASK5_SYSTEM_PROMPT = '\nYou are a biomedical decision-support model for immunotherapy survival risk prediction.\nUse only the supplied bulk-expression survival summary.\nDo not infer outcomes from cohort name, sample identifier, benchmark order, or formatting cues.\nHigher risk_score means shorter expected survival and earlier event under immunotherapy.\nTreat inflamed, antigen-presentation, and cytotoxic programs as potentially favorable context.\nTreat stromal TGF-beta, myeloid inflammation, exhaustion, and cell-cycle pressure as adverse context.\nUse the calibration snapshot explicitly.\nDistinguish favorable immune-active, excluded-inflamed, stromal-dominant, myeloid-exhausted, and proliferative-escape states.\nLow risk should usually require favorable_immune_ready to be true, low_risk_ready to be true, low_risk_blocked to be false, and calibrated_net_risk to be clearly negative.\nHigh risk should usually require high_risk_ready to be true and clearly dominant adverse evidence, not just mildly positive net risk.\nIf mixed_profile is true or calibrated_net_risk is near zero, keep the case intermediate instead of forcing a polar answer.\nIf excluded_inflamed_state is true, do not collapse the case to low risk even when antigen presentation remains high.\nIf stromal_dominant_state, myeloid_exhausted_state, or proliferative_escape_state is true, treat this as adverse context.\nUse intermediate-high scores for adverse-leaning mixed cases rather than pushing them into low risk.\nPrefer score smoothing before group changes: moderate adverse cases can stay intermediate with scores around 0.58 to 0.64.\nAllow a wider score spread: clear low-risk cases may be 0.18 to 0.32, intermediate-low cases may be 0.42 to 0.50, intermediate-mid cases may be 0.51 to 0.58, intermediate-high cases may be 0.59 to 0.66, and only strong high-risk cases should exceed 0.67.\nAvoid extreme low scores unless the sample is clearly low-risk-ready.\nDo not let proliferation alone determine the answer.\nReturn only JSON with risk_group, risk_score, and 3 short rationale items.\n'.strip()

def build_task5_messages(sample_summary: dict) -> tuple[str, str]:
    compact_summary = build_compact_task5_summary(sample_summary)
    user_prompt = '\n'.join(['Assess this sample for relative survival risk under immunotherapy using the supplied bulk-expression summary only.', 'Program activity reflects relative within-sample enrichment of curated tumor-immune ecosystem programs.', 'Balance favorable immune reserve against exclusion, stromal, myeloid, exhaustion, and proliferative escape risk.', 'Use the calibration snapshot as the main tie-breaker for mixed cases.', 'Keep mixed or near-balanced cases intermediate instead of forcing low or high risk.', 'Use high risk when adverse context is multi-axis and high_risk_ready is explicit.', 'Use low risk sparingly and avoid it when low_risk_blocked is true or excluded_inflamed_state is true.', 'Use low scores around 0.18 to 0.32 only when the summary clearly supports favorable_immune_ready and low_risk_ready.', 'For adverse-leaning intermediate cases, scores around 0.60 to 0.64 are often more appropriate than immediate high-risk calls.', 'Use intermediate-low scores around 0.42 to 0.50 for favorable-leaning but not fully low-risk cases.', 'Use scores at or above 0.67 only when the summary clearly supports high_risk_ready.', json.dumps(compact_summary, ensure_ascii=False, separators=(',', ':'))])
    return (TASK5_SYSTEM_PROMPT, user_prompt)

def build_compact_task5_summary(sample_summary: dict) -> dict:
    top_genes = []
    for feature in sample_summary.get('top_ranked_features', [])[:6]:
        item = {'gene_symbol': feature.get('gene_symbol'), 'value': feature.get('value')}
        if feature.get('biological_tags'):
            item['biological_tags'] = feature['biological_tags'][:2]
        if item['gene_symbol'] is None:
            item['feature_id'] = feature.get('feature_id')
        top_genes.append(item)
    top_themes = [{'theme': theme.get('theme'), 'matched_feature_count': theme.get('matched_feature_count')} for theme in sample_summary.get('biological_theme_snapshot', [])[:4]]
    top_programs = [{'program': program.get('program'), 'activity_level': program.get('activity_level'), 'relative_activity_score': program.get('relative_activity_score'), 'representative_genes': program.get('representative_genes', [])[:4]} for program in sample_summary.get('program_activity_snapshot', [])[:6]]
    ecology_snapshot = sample_summary.get('ecology_snapshot', {})
    calibration_snapshot = sample_summary.get('calibration_snapshot', {})
    return {'task_name': sample_summary.get('task_name'), 'dataset_name': sample_summary.get('dataset_name'), 'sample_id': sample_summary.get('sample_id'), 'prompt_version': TASK5_PROMPT_VERSION, 'top_ranked_genes': top_genes, 'dominant_biological_themes': top_themes, 'dominant_programs': top_programs, 'ecology_snapshot': {'inflamed_support_score': ecology_snapshot.get('inflamed_support_score'), 'immune_activation_score': ecology_snapshot.get('immune_activation_score'), 'exclusion_pressure_score': ecology_snapshot.get('exclusion_pressure_score'), 'suppressive_pressure_score': ecology_snapshot.get('suppressive_pressure_score'), 'proliferative_pressure_score': ecology_snapshot.get('proliferative_pressure_score'), 'immune_favorability_score': ecology_snapshot.get('immune_favorability_score'), 'barrier_pressure_score': ecology_snapshot.get('barrier_pressure_score'), 'adaptive_reserve_score': ecology_snapshot.get('adaptive_reserve_score'), 'proliferative_escape_score': ecology_snapshot.get('proliferative_escape_score'), 'immune_balance_score': ecology_snapshot.get('immune_balance_score'), 'immune_exclusion_gap': ecology_snapshot.get('immune_exclusion_gap'), 'net_risk_score': ecology_snapshot.get('net_risk_score'), 'net_risk_direction': ecology_snapshot.get('net_risk_direction'), 'dominant_adverse_axis_count': ecology_snapshot.get('dominant_adverse_axis_count'), 'strong_adverse_signal_count': ecology_snapshot.get('strong_adverse_signal_count'), 'strong_protective_signal_count': ecology_snapshot.get('strong_protective_signal_count'), 'dominant_protective_programs': ecology_snapshot.get('dominant_protective_programs', [])[:3], 'dominant_adverse_programs': ecology_snapshot.get('dominant_adverse_programs', [])[:3]}, 'calibration_snapshot': calibration_snapshot}
